In [2]:
import torch

In [3]:
t = torch.tensor([[1.,2.,3.], [4.,5.,6.]])

In [4]:
t.min()

tensor(1.)

In [5]:
t.min(dim=0)[0]

tensor([1., 2., 3.])

In [6]:
t[0]

tensor([1., 2., 3.])

In [7]:
t.mean(dim=0)

tensor([2.5000, 3.5000, 4.5000])

In [29]:
data = torch.tensor([[1., 2., 3.], [4.,5.,6.], [1., 1., 1.], [2., 2., 2.],
                    [1., 2., 3.], [4.,5.,6.], [1., 1., 1.], [2., 2., 2.]])
data

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.]])

In [30]:
targets = torch.tensor([0, 1, 0, 0, 1, 0, 1, 0])
targets

tensor([0, 1, 0, 0, 1, 0, 1, 0])

In [31]:
dataset = torch.utils.data.TensorDataset(data, targets)

In [32]:
dataloader = torch.utils.data.DataLoader(dataset, batch_size=4)

In [33]:
for i, (x, label) in enumerate(dataloader):
    print(i)
    print(x)
    print(label)

0
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.]])
tensor([0, 1, 0, 0])
1
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.]])
tensor([1, 0, 1, 0])


In [34]:
for i in range(1):
    print(i)

0


In [35]:
a = [[5:6], [7:8]]

SyntaxError: invalid syntax (<ipython-input-35-959874e2cb88>, line 1)

In [36]:
a = [5:6]

SyntaxError: invalid syntax (<ipython-input-36-acd5ddfb1c35>, line 1)

In [37]:
a = index(5, 6, 1)

NameError: name 'index' is not defined

In [39]:
lis = [1,2,3,4,5,6]
lis[slice(2,4)]

[3, 4]

In [41]:
tuple(lis)

(1, 2, 3, 4, 5, 6)

In [69]:
def unpack(l):
    l2 = l + [9]
    print(lis + l2)
    return tuple(lis + [None])

In [71]:
unpack(lis)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 9]


(1, 2, 3, 4, 5, 6, None)

In [46]:
a

1

In [47]:
b

2

In [48]:
c

3

In [49]:
d

4

In [50]:
e

5

In [62]:
torch.tensor([]).shape

torch.Size([0])

In [65]:
torch.zeros([115, 0])

tensor([], size=(115, 0))

In [72]:
sum([1,2,3])

6

In [59]:
torch.cat([], dim=0)

RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/CPUType.cpp:2127 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/QuantizedCPUType.cpp:297 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9654 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:258 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
