In [1]:
import torch
import torch.nn as nn

In [12]:
t = torch.tensor([[1, 2, 3],
                  [2, 3, 4],
                  [4, 5, 6]])

t2 = torch.tensor([[8, 12, 13],
                   [12, 13, 14],
                   [14, 15, 16]])

dataset = torch.utils.data.TensorDataset(t)
dataset2 = torch.utils.data.TensorDataset(t2)
dataset_combined = torch.utils.data.ConcatDataset([dataset, dataset2])

dataloader = torch.utils.data.DataLoader(dataset, batch_size=2)           
dataloader_combined = torch.utils.data.DataLoader(dataset_combined, batch_size=2)

In [28]:
dataloader.dataset[slice(0,7)]

(tensor([[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]]),)

In [24]:
dataloader_combined.dataset[slice(0,1)]

TypeError: '<' not supported between instances of 'slice' and 'int'

In [2]:
model = nn.Linear(10, 10)
optimizer = torch.optim.SGD(model.parameters(), lr=1.0)
lrs = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.5)
lrs2 = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=2.0)

In [16]:
print(optimizer.param_groups[0]['lr'])
lrs.step()
print(optimizer.param_groups[0]['lr'])
lrs.step()
print(optimizer.param_groups[0]['lr'])
lrs2.step()
print(optimizer.param_groups[0]['lr'])
lrs2.step()
print(optimizer.param_groups[0]['lr'])

1.0
0.5
0.25
0.5
1.0


In [12]:
model = nn.Linear(10, 10)
optimizer_params = {'lr': 1.0, 'weight_decay': 1e-5}
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, **optimizer_params)

TypeError: type object got multiple values for keyword argument 'lr'

In [13]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [14]:
import numpy as np

In [15]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
lrs = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.5)
lrs2 = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=2.0)

In [3]:
t = torch.tensor([[1.,2.,3.], [4.,5.,6.]])

In [4]:
t.min()

tensor(1.)

In [5]:
t.min(dim=0)[0]

tensor([1., 2., 3.])

In [6]:
t[0]

tensor([1., 2., 3.])

In [7]:
t.mean(dim=0)

tensor([2.5000, 3.5000, 4.5000])

In [29]:
data = torch.tensor([[1., 2., 3.], [4.,5.,6.], [1., 1., 1.], [2., 2., 2.],
                    [1., 2., 3.], [4.,5.,6.], [1., 1., 1.], [2., 2., 2.]])
data

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.]])

In [30]:
targets = torch.tensor([0, 1, 0, 0, 1, 0, 1, 0])
targets

tensor([0, 1, 0, 0, 1, 0, 1, 0])

In [31]:
dataset = torch.utils.data.TensorDataset(data, targets)

In [32]:
dataloader = torch.utils.data.DataLoader(dataset, batch_size=4)

In [33]:
for i, (x, label) in enumerate(dataloader):
    print(i)
    print(x)
    print(label)

0
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.]])
tensor([0, 1, 0, 0])
1
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.],
        [2., 2., 2.]])
tensor([1, 0, 1, 0])


In [34]:
for i in range(1):
    print(i)

0


In [35]:
a = [[5:6], [7:8]]

SyntaxError: invalid syntax (<ipython-input-35-959874e2cb88>, line 1)

In [36]:
a = [5:6]

SyntaxError: invalid syntax (<ipython-input-36-acd5ddfb1c35>, line 1)

In [37]:
a = index(5, 6, 1)

NameError: name 'index' is not defined

In [39]:
lis = [1,2,3,4,5,6]
lis[slice(2,4)]

[3, 4]

In [41]:
tuple(lis)

(1, 2, 3, 4, 5, 6)

In [69]:
def unpack(l):
    l2 = l + [9]
    print(lis + l2)
    return tuple(lis + [None])

In [71]:
unpack(lis)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 9]


(1, 2, 3, 4, 5, 6, None)

In [46]:
a

1

In [47]:
b

2

In [48]:
c

3

In [49]:
d

4

In [50]:
e

5

In [62]:
torch.tensor([]).shape

torch.Size([0])

In [65]:
torch.zeros([115, 0])

tensor([], size=(115, 0))

In [72]:
sum([1,2,3])

6

In [59]:
torch.cat([], dim=0)

RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/CPUType.cpp:2127 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/QuantizedCPUType.cpp:297 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9654 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:258 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]


In [1]:
d1 = {'a': 1}
d2 = {'b': 2}

In [3]:
d1.union(d2)

AttributeError: 'dict' object has no attribute 'union'

In [4]:
dict(d1, **d2)

{'a': 1, 'b': 2}

In [1]:
d = {1: "lol"}
d

{1: 'lol'}

In [3]:
d.update({1: 'troll'})
d

{1: 'troll'}

In [6]:
varying_args = {'a': [1, 2], 'b': [8, 9, 10], 'c': [-2]}

In [7]:
for key, values in varying_args.items():
    print(key)
    print(values)

a
[1, 2]
b
[8, 9, 10]
c
[-2]


In [8]:
import itertools

In [19]:
list(itertools.product(varying_args['a'], varying_args['b'], varying_args['c']))

[(1, 8, -2), (1, 9, -2), (1, 10, -2), (2, 8, -2), (2, 9, -2), (2, 10, -2)]

In [ ]:

[list(zip(x,list2)) for x in itertools.permutations(list1,len(list2))]